resume: /home/arivero/logs_2025/train_all_ps_pretrain_v4/model_1_10000.pt
load_encoder: True
load_fuse_generator: True
device: cuda:0
image_size: 224
K: 1
deterministic: False
seed: 13809409134
threads_per_rank: -1
train:
  min_lr: 1.0e-05
  max_lr: 3.0e-05
  iterations_until_max_lr: 60000
  num_epochs: 10
  batch_size: 2
  accumulate_steps: 5
  num_workers: 2
  log_path: logs/train_all_audio_video_cycle_v10
  log_losses_every: 10
  visualize_every: 50
  mask_ratio: 0.01
  mask_dilation_radius: 10
  mask_mouth: True
  swap_mouth: True
  save_every: 10000
  use_wandb: False
  Ke: 1
  use_base_model_for_regularization: True
  resume_epoch: 0
  train_scale_min: 1.2
  train_scale_max: 1.8
  stored_scale: 2.2
  test_scale: 1.6
  enable_residual_scaling: False
  initial_residual_scale: 0.001
  max_res_scale_iterations: 15000
  residual_schedule: cosine
  use_one_cycle_lr: False
  max_batch_len: 60
  split_overlap: 0
  loss_weights:
    landmark_loss: 1000.0
    perceptual_vgg_loss: 10.0
    reconstruction_loss: 100.0
    emotion_loss: 1.0
    jaw_regularization: 25.0
    eyelid_regularization: 25.0
    expression_regularization: 125.0
    shape_regularization: 25.0
    pose_regularization: 100.0
    cam_regularization: 100.0
    exp_res_regularization: 0.0
    shape_res_regularization: 0.0
    pose_res_regularization: 0.0
    cycle_loss: 1.0
    mica_loss: 0.0
    landmark_mouth_dist_loss: 10.0
    lipreading_loss: 10.0
    phoneme_loss: 1.0
    velocity_loss: 50.0
    pose_smoothness_loss: 1.0
  optimize_base_pose: False
  optimize_base_shape: False
  optimize_base_expression: False
  optimize_tater: True
  optimize_generator: True
  optimize_phoneme_classifier: True
  freeze_encoder_in_second_path: False
  freeze_generator_in_second_path: False
arch:
  backbone_pose: tf_mobilenetv3_small_minimal_100
  backbone_shape: tf_mobilenetv3_large_minimal_100
  backbone_expression: tf_mobilenetv3_large_minimal_100
  num_expression: 50
  num_shape: 300
  use_eyelids: True
  enable_fuse_generator: True
  enable_temporal_generator: True
  tater_base: True
  TATER:
    interp_down_residual: False
    use_interp_linear_layer: False
    downsample_rate: 3
    apply_linear_after_res: False
    Expression:
      use_base_encoder: False
      use_audio: True
      use_latent: True
      use_linear: True
      linear_size: 320
      use_linear_downsample: True
      add_to_flame: True
      init_near_zero: False
      init_scale: 1.0e-09
      pretrain_path: /home/arivero/logs_2025/train_all_ps_pretrain_v4/model_1_10000.pt
      CrossAttentionTransformer:
        positional_embedding: Sinusoidal
        num_layers: 6
        cross_layers: 4
        croncat_layers: 4
        final_dropout:
          enable: False
          prob: 0.1
        attention:
          d_model_1: 320
          d_model_2: 320
          d_model_C: 640
          dim_feedforward_1: 640
          dim_feedforward_2: 640
          dim_feedforward_C: 1280
          num_attention_heads: 2
          dropout: 0.1
          layer_norm_eps: 1.0e-12
    Shape:
      use_base_encoder: False
      use_linear: True
      use_latent: True
      add_to_flame: True
      linear_size: 320
      use_linear_downsample: True
      init_near_zero: False
      init_scale: 1.0e-09
      pretrain_path: /home/arivero/logs_2025/train_all_ps_pretrain_v4/model_1_10000.pt
      Transformer:
        positional_embedding: Sinusoidal
        num_layers: 6
        final_dropout:
          enable: False
          prob: 0.1
        attention:
          hidden_size: 320
          hidden_size_2: 640
          num_attention_heads: 8
          attention_probs_dropout_prob: 0.1
          layer_norm_eps: 1.0e-12
    Pose:
      use_base_encoder: False
      use_linear: True
      use_latent: True
      add_to_flame: True
      linear_size: 192
      use_linear_downsample: True
      init_near_zero: False
      init_scale: 1.0e-09
      pretrain_path: /home/arivero/logs_2025/train_all_ps_pretrain_v4/model_1_10000.pt
      Transformer:
        positional_embedding: Sinusoidal
        num_layers: 6
        final_dropout:
          enable: False
          prob: 0.1
        attention:
          hidden_size: 192
          hidden_size_2: 384
          num_attention_heads: 8
          attention_probs_dropout_prob: 0.1
          layer_norm_eps: 1.0e-12
    text_emb_size: 768
  Phoneme_Classifier:
    enable: True
    type: Linear
    use_latent: True
    Transformer:
      positional_embedding: Sinusoidal
      num_layers: 2
      final_dropout:
        enable: False
        prob: 0.1
      attention:
        hidden_size: 56
        hidden_size_2: 112
        num_attention_heads: 2
        attention_probs_dropout_prob: 0.1
        layer_norm_eps: 1.0e-12
render:
  full_head: False
dataset:
  iHiTOP:
    hdf5_path: /local/PTSD_STOP/iHiTOP_Preprocessed/data
    frame_step: 1
    max_data_idxs: 360000
    removed_frames_threshold: 0.1
    max_seg_len: 9999999
    min_seg_len: 9
    data_idxs: /local/PTSD_STOP/TATER/data_idxs/all_data_idxs_FINAL_300K.npy
    final_idxs_train: /local/PTSD_STOP/TATER/final_idxs/all_data_idxs_FINAL_300K_train.npy
    final_idxs_val: /local/PTSD_STOP/TATER/final_idxs/all_data_idxs_FINAL_300K_val.npy
    final_idxs_test: /local/PTSD_STOP/TATER/final_idxs/all_data_idxs_FINAL_300K_test.npy
    bad_files: /local/PTSD_STOP/TATER/final_idxs/all_data_idxs_FINAL_300K_bad_files.npy
    train_percentage: 0.84
    val_percentage: 0.08
    test_percentage: 0.08
  VOCASET:
    data_path: /home/arivero/VOCA
    frame_step: 1
    removed_frames_threshold: 0.15
    max_seg_len: 9999999
    min_seg_len: 3
    final_idxs: /local/PTSD_STOP/TATER/final_idxs/all_final_idxs_VOCASET.npy
    train_percentage: 1.0
    val_percentage: 0.0
    test_percentage: 0.0
  LRS3_percentage: 0.0
  LRS3_temporal_sampling: False
  MEAD_percentage: 1.0
  FFHQ_percentage: 0.0
  CelebA_percentage: 0.0
  MEAD_sides_percentage: 0.0
  sample_full_video_for_testing: False
